// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu39pt-lHespQqYVtLH8b6hVVmLgzky4c',
    appId: '1:165104859284:android:977018752f0c89d12ddc81',
    messagingSenderId: '165104859284',
    projectId: 'mowasalati-app',
    storageBucket: 'mowasalati-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz4jpciou9GHHYfU5fkxoK06VdOlAcvYk',
    appId: '1:165104859284:ios:b2cdc57bc00832a72ddc81',
    messagingSenderId: '165104859284',
    projectId: 'mowasalati-app',
    storageBucket: 'mowasalati-app.firebasestorage.app',
    iosBundleId: 'com.alzainy.tahadi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHpwJ1-rCCaBE9BJ5sCUHIs3IwDJpzSE',
    appId: '1:165104859284:web:ce9eaf7ccd2741f82ddc81',
    messagingSenderId: '165104859284',
    projectId: 'mowasalati-app',
    storageBucket: 'mowasalati-app.firebasestorage.app',
    authDomain: 'mowasalati-app.firebaseapp.com',
  );
}